SELECT 
    COLUMN_NAME AS 'Field',
    COLUMN_TYPE AS 'Type',
    IF(IS_NULLABLE = 'YES', 'YES', 'NO') AS 'Null',
    COLUMN_KEY AS 'Key',
    COLUMN_DEFAULT AS 'Default',
    EXTRA AS 'Extra'
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
  TABLE_SCHEMA = 'alx_book_store'", "TABLE_NAME = 'Books'
ORDER BY 
    ORDINAL_POSITION;
